// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juanmercurio/tp-go/internal/ports (interfaces: RepositorioUsuarios)
//
// Generated by this command:
//
//	mockgen --destination=./mock/repo_usuarios.go github.com/juanmercurio/tp-go/internal/ports RepositorioUsuarios
//

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	reflect "reflect"

	domain "github.com/juanmercurio/tp-go/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepositorioUsuarios is a mock of RepositorioUsuarios interface.
type MockRepositorioUsuarios struct {
	ctrl     *gomock.Controller
	recorder *MockRepositorioUsuariosMockRecorder
}

// MockRepositorioUsuariosMockRecorder is the mock recorder for MockRepositorioUsuarios.
type MockRepositorioUsuariosMockRecorder struct {
	mock *MockRepositorioUsuarios
}

// NewMockRepositorioUsuarios creates a new mock instance.
func NewMockRepositorioUsuarios(ctrl *gomock.Controller) *MockRepositorioUsuarios {
	mock := &MockRepositorioUsuarios{ctrl: ctrl}
	mock.recorder = &MockRepositorioUsuariosMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositorioUsuarios) EXPECT() *MockRepositorioUsuariosMockRecorder {
	return m.recorder
}

// AltaUsuario mocks base method.
func (m *MockRepositorioUsuarios) AltaUsuario(arg0 domain.Usuario) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AltaUsuario", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AltaUsuario indicates an expected call of AltaUsuario.
func (mr *MockRepositorioUsuariosMockRecorder) AltaUsuario(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AltaUsuario", reflect.TypeOf((*MockRepositorioUsuarios)(nil).AltaUsuario), arg0)
}

// BajaUsuario mocks base method.
func (m *MockRepositorioUsuarios) BajaUsuario(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BajaUsuario", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BajaUsuario indicates an expected call of BajaUsuario.
func (mr *MockRepositorioUsuariosMockRecorder) BajaUsuario(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BajaUsuario", reflect.TypeOf((*MockRepositorioUsuarios)(nil).BajaUsuario), arg0)
}

// BuscarTodos mocks base method.
func (m *MockRepositorioUsuarios) BuscarTodos() ([]domain.Usuario, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarTodos")
	ret0, _ := ret[0].([]domain.Usuario)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarTodos indicates an expected call of BuscarTodos.
func (mr *MockRepositorioUsuariosMockRecorder) BuscarTodos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarTodos", reflect.TypeOf((*MockRepositorioUsuarios)(nil).BuscarTodos))
}
