services:
  mysql:
    image: mysql:5.7
    container_name: datos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "33306:3306"
    volumes:
      # TODO: encontrar mejor lugar para esto
      - "../mysql-volume:/var/lib/mysql"
  app:
    image: monedas 
    container_name: monedas_container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
