services:
  mysql:
    image: mysql:5.7
    container_name: datos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "33306:3306"
    volumes:
      - "../mysql-volume:/var/lib/mysql"
      - "./mysql-config:/etc/mysql/conf.d"

  # app:
  #   image: monedas
  #   container_name: monedas_container
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped
  #   depends_on:
  #     - mysql

